#!/usr/bin/env bash
# install NginX web server

sudo apt-get update -y -qq && \
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www/html
sudo chmod -R u=rwx,g=rx,o=rx /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
