#!/usr/bin/env bash
#prints best school 10x.print hi on 9th line
i=1
while [[ $i -le 10 ]]; do
  if [[ $i -eq 9 ]]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((i++))
done
