#!/usr/bin/env bash
# loops 1-10 displays bad luck for the 4th loop iteration

i=1
while [[ $i -le 10 ]];
do
	if [[ $i -eq 4 ]];
	then
		echo "Bad luck!"
	elif [[ $i -eq 8 ]];
	then
		echo "Good luck!"
	else
		echo "Best School"
	fi
	i++
done
