#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59
hour=0
while [[ $hour -lt 12 ]]; do
  minute=1
  while [[ $minute -le 59 ]]; do
    printf "%02d:%02d\n" "$hour" "$minute"
    ((minute++))
  done
  ((hour++))
done

