#!/usr/bin/env bash
# configures an Ubuntu server

cp /etc/hosts ~/hosts.new
echo "localhost" "127.0.0.2" > ~/hosts.new
add_dns_entry "facebook.com" "8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
